name: Docker dev image

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to run the workflow on'
        required: true
        type: choice
        options:
          - main
          - develop

jobs:
  Set-date:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.set-date.outputs.date }}
    steps:
      - name: Set date env variable
        id: set-date
        run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_ENV

  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

  Login-GHCR:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  Login-DockerHub:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
  Deploy-latest:
    runs-on: ubuntu-latest
    needs: [Set-date, Checkout, Login-GHCR, Login-DockerHub]
    steps:
      - name: Build and push latest release
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: | 
            ghcr.io/toomas633/xmrig-proxy:dev
            docker.io/toomas633/xmrig-proxy:dev
          labels: |
            org.opencontainers.image.created=${{ needs.Set-date.outputs.date }}
            org.opencontainers.image.version=dev