name: Docker latest image

on:
  release:
    types: [created]
env:
  date: ""

jobs:
  Set-date:
    runs-on: ubuntu-latest
    steps:
      - name: Set date env variable
        run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_ENV
    
  Deploy-latest:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    needs: Set-date
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push latest release
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: | 
            ghcr.io/toomas633/xmrig-proxy:${{ github.event.release.tag_name }}
            ghcr.io/toomas633/xmrig-proxy:latest
            docker.io/toomas633/xmrig-proxy:${{ github.event.release.tag_name }}
            docker.io/toomas633/xmrig-proxy:latest
          labels: |
            org.opencontainers.image.created=${{ env.date }}
            org.opencontainers.image.version=${{ github.event.release.tag_name }}